# Generated by Django 4.0.3 on 2022-03-26 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='hometasks_list_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='courses.hometasks', verbose_name='Список ДЗ'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='lessons_block_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='courses.lessonsblock', verbose_name='Блок занятий'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='lessons_list_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='courses.lessonslist', verbose_name='Список уроков'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='subthemes_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='courses.subthemes', verbose_name='Подтемы'),
        ),
    ]
