# Generated by Django 4.0.3 on 2022-03-26 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_courses_hometasks_list_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='subthemes_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.subthemes', verbose_name='Подтемы'),
        ),
    ]
